#!/bin/bash

echo "System Information"
echo "• Executed By: $(whoami)"
echo "• Hostname: $(hostname)"
echo "• Server IP: $(hostname -I | awk '{print $1}')"
echo "• Public IP: $(curl -s ifconfig.me || echo 'Not connected')"
echo "• OS Type and Version: $(source /etc/os-release && echo $PRETTY_NAME)"
echo "• Kernel Version: $(uname -r)"
echo "• Architecture: $(uname -m)"
echo "• Virtualization: $(hostnamectl | grep Virtualization | awk '{print $2}' || echo 'VirtualBox')"
echo "• Server Time: $(date)"
echo "• Timezone: $(timedatectl | grep "Time zone" | awk '{print $3, $4, $5}')"
echo "• Uptime: $(uptime -p | sed 's/up //')"
echo ""
echo "Resource Usage"
echo "• Total Memory: $(free -h | awk '/^Mem:/ {print $2}')"
echo "• Memory Usage: $(free -h | awk '/^Mem:/ {print $3 " / " $2}')"
echo "• Swap Usage: $(free -h | awk '/^Swap:/ {print $3 " / " $2}')"
echo "• CPU Cores: $(nproc)"
